# Generated by Django 3.1.6 on 2021-12-11 13:33

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок на русском')),
                ('image', models.ImageField(upload_to='images')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок на кыргызском')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=50, verbose_name='Вопрос')),
                ('answer_ru', models.TextField(blank=True, verbose_name='Ответ')),
                ('question_kg', models.CharField(max_length=50, verbose_name='Суроо')),
                ('answer_kg', models.TextField(blank=True, verbose_name='Жооп')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок на русском')),
                ('title_kg', models.CharField(max_length=200, verbose_name='Заголовок на кыргызском')),
                ('body_ru', django_quill.fields.QuillField(verbose_name='Тело поста на русском')),
                ('body_kg', django_quill.fields.QuillField(verbose_name='Тело поста на кыргызком')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('slug_id', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
