# Generated by Django 3.1.6 on 2021-12-02 19:38

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210204_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_kg',
            field=django_quill.fields.QuillField(verbose_name='Тело поста на кыргызком'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_ru',
            field=django_quill.fields.QuillField(verbose_name='Тело поста на русском'),
        ),
    ]
