# Generated by Django 3.1.6 on 2021-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
